version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    ports: 
      - "3001:3001"
    environment:
     - DATABASE_URL=postgres://guruuser:gurupass@db:5432/gurudb
     - PORT=3001
     - SECRET_JWT=secret
  db:
    image: postgres:14
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=guruuser
      - POSTGRES_PASSWORD=gurupass
      - POSTGRES_DB=gurudb