version: "3.9"

services:
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "3001:3001"
    environment:
     - DATABASE_URL=postgres://root:gurupass@db:5555/root
     - PORT=3001
     - JWT_SECRET=secret
  db:
    image: postgres:14
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=gurupass
      - POSTGRES_DB=root